### ISSUE TITLE
pls add 'remove fully' option to remove() function

### ISSUE THREAD

**Issue by fiag** [zkat/cacache-rs#53]
According the npm/cacache [rm.entry](https://www.npmjs.com/package/cacache#rm-entry) API 
```
By default, this appends a new entry to the index with an integrity of null. If opts.removeFully is set to true then the index file itself will be physically deleted rather than appending a null
```
thanks a lot!

**Comment by zkat** [comment]
doing this would mean that the index would no longer be atomic. That's why deletions are done through appending null.

the JS version of cacache has a [`verify()`](https://www.npmjs.com/package/cacache#--cacacheverifycache-opts---promise) method that is expected to be called in a "locked" environment when nothing else is running. I'd like to have that in cacache-rs too.
